zip_url <- "https://github.com/mbadolato/iTerm2-Color-Schemes/archive/refs/heads/master.zip"
zip_path <- "iterm.zip"
staging_dir <- "iterm"
theme_dir <- file.path(staging_dir, "iTerm2-Color-Schemes-master", "vscode")
output_path <- file.path("R", "palettes-iterm.R")

if (file.exists(zip_path)) unlink(zip_path)
if (dir.exists(staging_dir)) unlink(staging_dir, recursive = TRUE)

download.file(zip_url, destfile = zip_path, mode = "wb", quiet = TRUE)
unzip(zip_path, exdir = staging_dir)

if (!dir.exists(theme_dir)) stop("Can't locate VS Code theme directory in downloaded archive.", call. = FALSE)

# Collect all available themes and keep deterministic ordering for reproducible output
theme_paths <- sort(list.files(theme_dir, pattern = "\\.json$", full.names = TRUE))
theme_names <- tools::file_path_sans_ext(basename(theme_paths))

# Map palette labels to the ANSI color keys exposed by each theme.
normal_keys <- c(
  Blue = "terminal.ansiBlue",
  Yellow = "terminal.ansiYellow",
  Red = "terminal.ansiRed",
  Cyan = "terminal.ansiCyan",
  Green = "terminal.ansiGreen",
  Magenta = "terminal.ansiMagenta"
)

bright_keys <- c(
  Blue = "terminal.ansiBrightBlue",
  Yellow = "terminal.ansiBrightYellow",
  Red = "terminal.ansiBrightRed",
  Cyan = "terminal.ansiBrightCyan",
  Green = "terminal.ansiBrightGreen",
  Magenta = "terminal.ansiBrightMagenta"
)

# Extract a named character vector for the requested variant, failing fast if
# any expected key is missing so we notice upstream changes in the archive.
make_variant <- function(theme, keys, name, variant) {
  vapply(
    keys,
    function(key) {
      value <- theme[[key]]
      if (is.null(value)) {
        stop(
          sprintf(
            "Theme '%s' is missing key '%s' for the '%s' variant.",
            name,
            key,
            variant
          ),
          call. = FALSE
        )
      }
      toupper(value)
    },
    character(1)
  )
}

format_assignment <- function(name, variant, values) {
  lines <- sprintf('  "%s" = "%s"', names(values), unname(values))
  if (length(lines) > 1) {
    lines[-length(lines)] <- paste0(lines[-length(lines)], ",")
  }
  c(sprintf('ggsci_db_iterm$"%s"$"%s" <- c(', name, variant), lines, ")")
}

format_palette <- function(path, name) {
  theme <- jsonlite::read_json(path)$workbench.colorCustomizations
  normal_values <- make_variant(theme, normal_keys, name, "normal")
  bright_values <- make_variant(theme, bright_keys, name, "bright")
  c(
    format_assignment(name, "normal", normal_values),
    "",
    format_assignment(name, "bright", bright_values),
    ""
  )
}

palette_lines <- unlist(Map(format_palette, theme_paths, theme_names), use.names = FALSE)

if (length(palette_lines) && palette_lines[length(palette_lines)] == "") {
  palette_lines <- palette_lines[-length(palette_lines)]
}

header_lines <- c(
  "# Generated by tools/update_iterm_palettes.R: do not edit by hand",
  "# Please run Rscript tools/update_iterm_palettes.R to regenerate this file",
  "",
  "#' iTerm color palette names",
  "#'",
  "#' @return Character vector of palette names.",
  "#'",
  "#' @export iterm_palettes",
  "#'",
  "#' @examples",
  "#' iterm_palettes()",
  "iterm_palettes <- function () {",
  "  c(",
  paste0('    "', theme_names, '"', collapse = ",\n"),
  "  )",
  "}",
  "",
  "ggsci_db_iterm <- vector(\"list\")",
  ""
)

output_lines <- c(header_lines, palette_lines)

writeLines(output_lines, con = output_path)

unlink(zip_path)
unlink(staging_dir, recursive = TRUE)
